# Generated by Django 4.2.2 on 2023-08-05 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweeahs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeah',
            name='retweeted_by',
            field=models.ManyToManyField(blank=True, related_name='retweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
