# Generated by Django 4.2.2 on 2023-08-07 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweeahs', '0003_tweeah_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweeah',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='tweeah',
            name='retweet_count',
        ),
        migrations.AddField(
            model_name='tweeah',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
