# Generated by Django 4.2.2 on 2023-10-29 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweeahs', '0004_remove_tweeah_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweeah',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tweeah',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarked', to=settings.AUTH_USER_MODEL, verbose_name='bookmarks'),
        ),
    ]
